### ISSUE TITLE
Blocked from responding on particular issue !!!!

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#126]
@lightswitch05  just a heads up. Just noticed that i can no longer respond on one of your repo's issues  #125  and in @crazy-max's https://github.com/crazy-max/WindowsSpyBlocker/issues/200#issuecomment-578483979.
I'm more then certain that this shady person 👎  @beerisgood 👎  is behind it,very likely he is Microsoft's employee working in GitHub.He's been crusading for a long time in every repo that provides blocklists advocating for removal of Microsoft's domains.
Please thread carefully before you decide to remove anything else requested by him and would advise to review his past requests as well.
Regards 👍 

![lightswitch05](https://user-images.githubusercontent.com/34774426/73138450-4ba20400-4028-11ea-8912-90673e626296.png)

**Comment by llacb47** [comment]
Me neither, same thing happened to me with  spirillen

**Comment by lightswitch05** [comment]
the ticket in question has been closed, so I think this one is done too.

**Comment by lightswitch05** [comment]
Just in case there are any concerns about microsoft and github. I do have a mirror of this repo over at gitlab: https://gitlab.com/lightswitch05/hosts

I DO NOT recommend using it since it is regularly out of date. But if something ever happened with this repo, there are other sources. I also do not monitor it, so please do not open tickets over there.

**Comment by llacb47** [comment]
By the way I was the one who marked my own link off-topic... ¯\_(ツ)_/¯

**Comment by dnmTX** [comment]
Thanks @lightswitch05 👍
