### ISSUE TITLE
CDN77.org blocked even though it is a normal CDN

### ISSUE THREAD

**Issue by owah** [lightswitch05/hosts#140]
Hi,

I can understand that some of the stuff which is served on cdn77 might be ads/trackers, but the CDN itself is not malicious and the root domain should not be included in the blocklist.

**Comment by lightswitch05** [comment]
Hi @owah can you provide multiple examples?

**Comment by owah** [comment]
Well according to their website https://www.cdn77.com/ they serve some big names, CentOS, plesk, the european space agency. The spacetelescope website mentions on the bottom that they are accelerated by cdn77: https://www.spacetelescope.org/images/heic0715a/

Centos mentions here that CDN77 sponsors them: https://www.centos.org/sponsors/

Virustotal also doesn't report anything suspicious for the base url
https://www.virustotal.com/gui/url/b189fac40110fc857f3c573e6e2fd72e6616aa9d360c2ecf11eddbdd357cd287/detection

https://www.virustotal.com/gui/url/0286f379faecc5dcdba5075c0c5e67b2c41946f3360957c7dbdde462dfda19b8/detection

Again, I am not saying that some CDN77 customers might embed tracking in their served files, but the CDN itself is not malicious.

**Comment by lightswitch05** [comment]
This is a very low effort request.

1: I asked for multiple examples where `cdn77.org` was being used. You did not provide a single example. Yes, `spacetelescope.org` uses them as a CNAME alias for `cdn.spacetelescope.org` - but that's not using them directly.
2. This is an advertising and tracking blocklist. It is not a malicious domain blocklist. What VirusTotal has to say makes no difference to me. Not to say I do no have malicious domains in my list - it just so happens that advertising is often malicious.
3. I don't care who `cdn77.org` sponsors
4. I haven't had my coffee yet

Ok despite all that, I agree that this host is way too generic to be blocked and I'll remove them. I was pissed off by the amount of advertisers that had access to my tax information while filling out my taxes on `taxact.com` when I added this host, so I overreacted a bit. I'm leaving `1605158521.rsc.cdn77.org` because that was the offender. In the future, please provide some more concrete examples when making a whitelist request 👍 

As a side note, here are all the hosts that came from taxact alone. Not their landing page, but after you've already purchased their invasive service and are filling out your taxes: https://github.com/lightswitch05/hosts/commit/82180d67

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/0611d7f930ad2a89674abcf03d46443ffbe3aaa7

Thank you for bringing it to my attention @owah
