### ISSUE TITLE
8 IDN domains on ads-and-tracking-extended.txt

### ISSUE THREAD

**Issue by yubiuser** [lightswitch05/hosts#145]
Thanks for providing this list. 
Since the last update pihole complains about 8 invalid domains on ads-and-tracking-extended list.
The first 5 are
      - ɢoogletranslate.com
      - accounts.ɢoogletranslate.com
      - ɢoogle.company
      - ɢoogle.email
      - ɢoogle.life

Looks like the "G" is not an ASCII "G" and the domains used for IDN homograph attacks. Could you convert them to punycode before adding them? Pihole can deal with punycode in the upcoming v5.0 and those domains can be filtered out.
Thank you.

**Comment by lightswitch05** [comment]
Hello @yubiuser, thank you for opening this ticket.

* Those hosts were added in https://github.com/lightswitch05/hosts/commit/e4bc463d0b95ce874a0251b29a7fea9af722a2c6
* I also included the punycode versions when I added those to my list

My understanding is that pihole will just ignore the domains that it considers invalid and will continue using the rest of the list. Since this is a hosts formatted list that can be used by many tools other then pihole, I wanted to be sure to include both versions of the domains to ensure they get blocked regardless of the tool's support for punycode. As long as the changes are not breaking anything, I think I prefer to have those domains remain in the list.

**Comment by yubiuser** [comment]
Yes, you are right - pihole just ignores those lines. I can see your point in keeping the IDN names.
Maybe I just have to rename what I really want: **additionally** add IDN domains as punycode.

**Comment by lightswitch05** [comment]
Look at the diff, I added them: https://github.com/lightswitch05/hosts/commit/e4bc463d0b95ce874a0251b29a7fea9af722a2c6

**Comment by yubiuser** [comment]
Thanks
