### ISSUE TITLE
accounts.us1.gigya.com socialize.us1.gigya.com   False Positive

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#146]
Hi, you are blocking the following domains:

accounts.us1.gigya.com
socialize.us1.gigya.com

These domains break logging into iRobot app on Android, and starting iRoomba vacuum from Google Home

**Comment by lightswitch05** [comment]
Well its certainly not a false positive. I think the issue here is that either iRoomba app has very poor error handling, or even more likely they are just letting this tracking service do everything for them in the app so they don't have to. I think this is probably a good use-case for the 'opt-in' approach, where you basically opt-in to their data tracking by whitelisting the domain on your end.

Lets leave this ticket open for a while to see if anyone else is having issues.

**Comment by lightswitch05** [comment]
Oh, looking into this more. only `socialize.us1.gigya.com` is blocked in the primary ads-and-tracking list. `accounts.us1.gigya.com` is blocked in the tracking aggressive list, which seems appropriate.

**Comment by lightswitch05** [comment]
I originally moved the `gigya` hosts to the aggressive list here: https://github.com/lightswitch05/hosts/commit/25634301fb15c2f8c9011fef0c48e83a007d4d73

**Comment by lightswitch05** [comment]
The socialize subdomain was added in https://github.com/lightswitch05/hosts/commit/e5782757

**Comment by p1r473** [comment]
Okay, thank you

**Comment by donateur** [comment]
**For anyone finding this through a search engine:**
A recent update to the iRobot app for Android forced me to whitelist `accounts.us1.gigya.com` ONLY.  I was able to still use the app with ` socialize.us1.gigya.com` blocked.
