### ISSUE TITLE
False Positve - *.greenhouse.io 

### ISSUE THREAD

**Issue by BPitts2** [lightswitch05/hosts#159]
Hello,

I'd like to petition that greenhouse.io is removed from this list.

Greenhouse is a job recruiting and applicant tracking system for HR organizations. The current block list is blocking basically everything at greenhouse.io

This prevents people from viewing integrated job boards on company websites, applying to those jobs, and viewing the status of those applications.

Reference Materials -
https://en.wikipedia.org/wiki/Greenhouse_Software

**Comment by lightswitch05** [comment]
Thanks for the report @BPitts2.

Added in https://github.com/lightswitch05/hosts/commit/afe8e924

>  Added some more commonly blocked hosts as well as greenhouse from pihole and techtarget from their own website

The problem here is that I'm not looking for a job and I was seeing a lot of requests for `boards.greenhouse.io` on my network. Unfortunately, the requests are coming from my phone - so tracking it down is a little difficult. Can you give me any insights @BPitts2 what might be doing this and how `boards.greenhouse.io` is being used?

**Comment by XhmikosR** [comment]
Actually, I've been meaning to report this myself.

Many companies use Greenhouse for job listings and I agree it shouldn't be blocked IMO.

**Comment by lightswitch05** [comment]
@XhmikosR can you provide any insights if `boards.greenhouse.io` is doing tracking?

**Comment by XhmikosR** [comment]
No insight, sorry. But it's a legit job applications platform.

**Comment by XhmikosR** [comment]
For what is worth, I also see `boards.greenhouse.io` in https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt

Unfortunately, I cannot know if they do tracking and what exactly they are doing. I know for sure that legit job applications are posted on greenhouse. For example https://twitter.com/search?q=boards.greenhouse.io

**Comment by lightswitch05** [comment]
@BPitts2 do you have any information about potential insight/tracking related to `boards.greenhouse.io`?

**Comment by XhmikosR** [comment]
Thanks @lightswitch05!
