### ISSUE TITLE
Maxmind domains

### ISSUE THREAD

**Issue by p1r473** [lightswitch05/hosts#163]
I believe these may be a false positives. They are on the aggresive blocklist, but I think this is more than aggresive- this is just blocking the entire company.

Maxmind is a legitimate company that specialized in both Fraud Detection, as well as the geolocation databases.

They create an  Apache webplugins that can do geolocation. I am using their geolocation database to block Russian/Chinese/Iranian IPs from getting into my Apache server.
I can not find any tracking on their domains.

dev.maxmind.com
Their dev domain is meant for developers and contains great howtos and guides and tutorials.
i.e. https://dev.maxmind.com/geoip/legacy/mod_geoip2/

updates.maxmind.com
This domain is used to serve geoIP updates. I use this on my Pi to update all of the databases.
This domain is called when you update using /usr/local/bin/geoipupdate and without it, the updates fail.
```root@TinkerBoardS:/home/linaro # geoipupdate
curl_easy_perform() failed: Couldn't connect to server
Connect to https://updates.maxmind.com/app/update_getfilename?product_id=GeoLite2-ASN```
```

maxmind.com / www.maxmind.com /www2.maxmind.com
Their main domain. Mostly sales-y stuff

static.maxmind.com
This contains all their assets to load on their site. Without it, the main page doesnt load.

Just going through the rest of the domains you blocked.... I think going through this one by one will take forever, but you seem to have really done a number on these guys..

A bunch of git/github/geoIP related domains too
geoip.maxmind.com
geoip-as-southeast.maxmind.com
geoip-ipv4.maxmind.com
geoip-js.maxmind.com
geoip-us-east.maxmind.com
geoip1.maxmind.com
geoip2.maxmind.com
geoip3.maxmind.com
geoip4.maxmind.com
geolite.maxmind.com
git.maxmind.com
github.maxmind.com
...
Updates,suppor,servicestatus
status.maxmind.com
support.maxmind.com
update.maxmind.com
updates.maxmind.com
...
Deployments, email, marketing, download links...
deployments.maxmind.com
device.maxmind.com
download.maxmind.com
email.maxmind.com
marketing.email.maxmind.com
o1.email.maxmind.com
...
Load testing and logs
loadtest.maxmind.com
logs.maxmind.com
www.logs.maxmind.com
...
APIs and Alerting things
alertmanager.maxmind.com
alertmanager-test.maxmind.com
api.maxmind.com
api-v4.maxmind.com

I am sure you have not seen tracking, ads, or anything malicious on all of these domains. Did you just block all of their subdomains?  This is a useful and non malicious company. Can you take a closer look at why you have blocked this all? Maybe you had a bad experience with them?

**Comment by lightswitch05** [comment]
See #55

> Maxmind is a legitimate company that specialized in both Fraud Detection, as well as the geolocation databases.

Yes, geolocation data - which is used for tracking. They have a javascript `geoip-js.maxmind.com` - that I block in the primary list.

> Did you just block all of their subdomains

Yes, this is how my lists works. When I add a host, all the subdomains are automatically discovered and also added to the list. In this case, I blocked `maxmind.com`.

> This is a useful and non malicious company.

Yes, knowing IP locations has a legitimate use. I myself block all IP ranges for certain countries. However, it also IP location also has the use for targeting and tracking, and I would wager that is the majority of use cases for Maxmind. I agree with you that its aggressive, but considering its on the aggressive list I think that is ok. Looking again at my list description for the aggressive list:

> A very aggressive block list for tracking, **geo-targeting**, & ads. This list will likely break functionality, so do not use it unless you are willing to maintain your own whitelist.

Considering Maxmind is for geotargeting - I think its a perfect fit.

**Comment by lightswitch05** [comment]
I just wanted to add @p1r473 - thank you for putting effort into asking this question. It was a very well written question and breaking the different subdomains into groups really shows how much you researched it. I appreciate well researched questions and I don't want you to think that effect went unnoticed.

Some history on the aggressive list: I created it after receiving a ton of complaints about blocked hosts that I wanted to continue blocking. I use these lists personally, its a convenient way for me to maintain a blocklist between two different piholes, uBlock origin, and uMatrix. I started moving hosts out of my primary list and into this aggressive list to make people happy while still being able to keep them blocked for myself.

I want this host blocked personally. Yes, adding the entire root domain is aggressive, but I also don't want to have to keep monitoring their hosts to see if they've added any new ones that need to be blocked. If I took action on this request, then it would mean creating a third list - something like 'my-personal-blocklist', which I do not want to do, and would probably still receive whitelist requests for.

I have removed hosts from the aggressive list in the past, but that was due to being convinced it was a complete mistake and false positive. I do not believe that is the case here.

**Comment by p1r473** [comment]
@lightswitch05 Well I planned on going one domain at a time, but I kept finding more and more blocked ones, then I just starting grouping them haha :) then once I realized that you just blocked the entire domain, I stopped giving good comments! But I started off good!

I understand not wanting to create both an aggressive vs a personal blocklist- but I will give one counter argument- many many people use your list. It feeds right into the Ultimate Block List, and many others too. So there is something to be said for creating a personal blocklist for yourself, and an aggressive blocklist that services the public (because so many people use your list now.

If you do that, you could have ```geoip-js.maxmind.com``` in your primary blocklist, and all the rest in your personal blocklist. I am not sure how many hours it would take you to sort aggressive and personal into separate lists, but just remember, there are 1000s of people using your blocklist, as it feeds into many other lists.

I also do get that the aggressive list originally was your personal blocklist, but as the aggressive list was good too, many other lists started including your aggressive list in their list. It is kind of ironic!

Just my 2 cents! But I respect your decision- No problem at all- I have whitelisted Maxmind on my end. Just some constructive criticism.

Keep up the great work and thanks for your always indepth replies. :)

**Comment by lightswitch05** [comment]
> I also do get that the aggressive list originally was your personal blocklist, but as the aggressive list was good too, many other lists started including your aggressive list in their list. It is kind of ironic!

I'm not convinced the same thing wouldn't happen to a 'personal' list, but I'll keep the suggestion in mind.

Right now I'm in the middle of a complete rewrite of this entire project. I'm putting it all into a database with an API, web interface, and automatic scheduled tasks. From user's point of view nothing will change since it will all be hosted at my home. However, it will allow me to more easily make modifications - particularly on my phone - as well as keep better notes about why things are blocked. Also, the logic for finding subdomains will be greatly improved. I have no idea when it will all get it done, but anyways, too many moving parts to consider another list at this moment.

**Comment by p1r473** [comment]
Looking forward to it! Thanks :)
