### ISSUE TITLE
Target.com blocking is too aggressive?

### ISSUE THREAD

**Issue by jmcnevin** [lightswitch05/hosts#18]
I've noticed that the blocking of `api.target.com`, `profile.target.com`, and `redsky.target.com` makes the Target iOS app totally unusable.

**Comment by lightswitch05** [comment]
@jmcnevin I've removed `api.target.com`, `profile.target.com`, and `stage.api.target.com`. I hope this fixes your problems. I'm going to go ahead and close this issue and recommend any further comments or issues be added to #19 since it has more details. Please let me know if you continue to have problems
