### ISSUE TITLE
Video breakage at cbsnews.com

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#183]
Rule `||tealium.cbsnews.com^` on `Lightswitch05's ads-and-tracking-extended.txt` breaks video at `https://www.cbsnews.com/news/spacex-launch-watch-nasa-astronauts-docking-space-station-time-stream-today/`.

Currently adding `@@||tealium.cbsnews.com^$script,1p` resolves situation.

Cheers

**Comment by lightswitch05** [comment]
Thanks for the report @crssi - unfortunately your solution is not compatible with a hosts formatted list.

**Comment by crssi** [comment]
That is unfortunate, yes. Just forgot that its hosts oriented. 😉
How can I follow the reason that domain got to your list, in this case the `tealium.cbsnews.com`?

Cheers

**Comment by lightswitch05** [comment]
Added by b7232a5e2a3a68eb1bd76127fc4b7f5bd0733f04  added some trackers and bidders from cbsnews.com

I’ll reevaluate it next opportunity I have

**Comment by crssi** [comment]
I am asking how, to take some work off your shoulders? 😉 
This case it is not some "deal breaker", but I had to see plush dragon inside the crew dragon capsule. 😄 

Anyway, thank you for your work.

**Comment by lightswitch05** [comment]
Oh thanks for the offer. These lists are generated from some custom tools I’ve created. That means a direct change in this repo would just get overwritten the next time I generate them. It’s pretty easy for me to add and removing things, but I always verify the reports before adding or removing- which is the part that take time. I can do pretty much everything from my phone now except for the verification step.

**Comment by crssi** [comment]
I see. Feel free to close this issue when appropriate for you. 😉 
Thank you an cheers

**Comment by lightswitch05** [comment]
What an absolute broken piece of crap website. For me to get this to work, I had to whitelist:

* `tealium.cbsnews.com`
* `securepubads.g.doubleclick.net`
* `public.vilynx.com`
* `dpm.demdex.net`

Not only was my list breaking the website, but also 'Privacy Badger' and Firefox's built-in tracking protection had to be disabled before I could get it to work. I don't believe all these things are actually required for the video to play, but the website has poor error handling and just breaks if something is blocked.

I've fine with adding whitelisting `tealium.cbsnews.com` since it is specific to this site. The actual video is coming from `public.vilynx.com` - so I've created a whitelist for that too.

However, I will not be removing the other domains (`dpm.demdex.net`, `securepubads.g.doubleclick.net`)
