### ISSUE TITLE
The commercial URL shortener service for creating affiliate links — geni.us

### ISSUE THREAD

**Issue by mestrogov** [lightswitch05/hosts#193]
[geni.us](https://geniuslink.com) is the link shortener service designed for efficient management of affiliate links on some retailers' websites.

So I believe it is worth removing it from the blocklist as it is highly likely a false-positive since other URL shortening services (e.g. bit.ly) is not currently blocked 👍

**Comment by lightswitch05** [comment]
I don't really like affiliate links.... a long time ago I actually had `buff.ly` in the main list too and I was convinced to move it in ecdc1569289c2e3770628eb8595e62bc11c0f689

But I understand how frustrating it can be to click on something and have the link break. Personally, I like it to break, because then I realize that what I clicked on was paid for. This can happen from sites where it is not obvious that there is an incentive - like a blog post. Knowing its a paid affiliate link lets me re-evaluate why I clicked on it initially. Anyways, getting off track... going to move this to the aggressive list.

**Comment by lightswitch05** [comment]
btw, this was added due to:

>  CNAME value for target.georiot.com - looks like link tracking crap 

```
id 16850
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
target.georiot.com. IN A
;ANSWER
target.georiot.com. 21084 IN CNAME geni.us.
geni.us. 59 IN A 45.55.103.3
;AUTHORITY
;ADDITIONAL
```

**Comment by lightswitch05** [comment]
Fixed in https://github.com/lightswitch05/hosts/commit/2e73d047f33f642394551de2bca0936f031ff967
