### ISSUE TITLE
False positive: vk.com

### ISSUE THREAD

**Issue by sayl1th** [lightswitch05/hosts#205]
False positive: vk.com and subdomains. It's a russian social network and very popular.

**Comment by lightswitch05** [comment]
Thanks for the report @sayl1th 

It was added in https://github.com/lightswitch05/hosts/commit/c2cc39b08486a4695be7b4f3258dadd19e9b5913

Unfortunately, much like facebook, `kv.com` does general tracking online - not just limited to their website:

for example, on `livejournal.net`, you'll see it loading script: `https://vk.com/js/api/openapi.js?168`

Since this is already in the tracking aggressive list, then I don't think I'm going to take any further action. I generally recommend people to not use that list, and if something breaks, it is on the user to whitelist it on their end.
