### ISSUE TITLE
sascdn.com subdomains causing breaking site

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#209]
See https://github.com/NanoMeow/QuickReports/issues/4403

Blocking `r.sascdn.com` and `ced-ns.sascdn.com` breaks the video here: `https://ubeat.tv/v/ubeat-crew-con-widler-dormir-esposados-es-horrible`

**Comment by lightswitch05** [comment]
![image](https://user-images.githubusercontent.com/598803/88711731-9b9c7900-d0e6-11ea-865e-8bff91a2307b.png)

failed due to improper error handling. I appreciate that Easylist is able to whitelist it on this specific domain, but since I'm not able to do that, I'm not inclined to whitelist based on this single failure. If it becomes a widespread issue, then I'll reconsider. As always, thanks for the report @llacb47!

**Comment by lightswitch05** [comment]
Their crappy website has been fixed to no longer break when things a blocked.
