### ISSUE TITLE
intel.com blocked in ads-and-tracking-extended.txt

### ISSUE THREAD

**Issue by mmotti** [lightswitch05/hosts#210]
It has been brought to my attention by somebody that intel.com seems to be mistakenly listed

https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by lightswitch05** [comment]
Oh man, this is a bad one, thanks for the report!

This is an automatic entry- that is supposed to only happen on subdomains:

`Common crawl result when searching for www91.intel.com`

From the result, it appears it's adding the root domain of it starts with a `www`. That entry is valid:

> www91.intel.com","notes":"Just CNAME target to intel.com.ssl.sc.omtrdc.net


It's going to take me a little while to research this one and get the bad entries cleaned up. Thanks again for the report!

**Comment by lightswitch05** [comment]
bug introduced by https://github.com/lightswitch05/hosts/issues/194

Added validation to ensure all entries added are actual subdomains. However, there is no great way for me to clean up the existing data - so I ended up just dropping it all. It will show back up in a few weeks.

Fixed by https://github.com/lightswitch05/hosts/commit/3aa6abf8bd01dddda0e7e2b62cb872d59d6e3639

Thanks for the report!
