### ISSUE TITLE
www.cultofmac.com CNAME www-cultofmac-com.ezoic.net

### ISSUE THREAD

**Issue by ACMEd** [lightswitch05/hosts#219]
https://www.cultofmac.com/ requires `www-cultofmac-com.ezoic.net` (The former being a CNAME of the latter).

**Comment by lightswitch05** [comment]
Root domain `ezoic.net` added in https://github.com/lightswitch05/hosts/commit/e35f2c56dd2e59d6ae4a055a2cab36ee068c9628 - commit message is junk, but looks like the two domains I had issues with were `g.ezoic.net` and `go.ezoic.net`

looking at other lists, I'm not the only one blocking the root domain, but of course my list is a bit different where it auto-expands subdomains. Since this CNAME is specific to this website and not some generic widely used domain, then I'm happy to add a whitelist for it.

**Comment by lightswitch05** [comment]
Fixed by https://github.com/lightswitch05/hosts/commit/3f7e9979c96d68a03ca6d997ae0c6ac44087a8ea

Thanks for the report @ACMEd!
