### ISSUE TITLE
Blocking cdn.ravenjs.com breaks Dixa.com login

### ISSUE THREAD

**Issue by Laurisade** [lightswitch05/hosts#223]
https://dixa.com/signin?noToken=true

Using NextDNS with Ads & Tracking.
Login window does not load when cdn.ravenjs.com is blocked. Practically the site fails to load.

Once this domain is whitelisted, I could log in :)
![image](https://user-images.githubusercontent.com/6094860/91011155-753a0280-e5ec-11ea-87b1-8babea6d1fd4.png)

Could you please whitelist this domain?

**Comment by lightswitch05** [comment]
No, see #58.

The good news is that this domain isn't required fir the website to work, it's just poor error handling breaking it, so perhaps they will fix it.

**Comment by lightswitch05** [comment]
Some history on why sentry would break a website: https://github.com/getsentry/sentry-docs/pull/814

**Comment by Laurisade** [comment]
Thanks a lot for prompt reply.

Everything is clear, should have searched (thought it is more of a isolated case) 👍

**Comment by lightswitch05** [comment]
Yes, I've confirmed the login page breaks due to unsafe usage of the global `Raven`: `Uncaught ReferenceError: Raven is not defined`.  

Perhaps @ktabori could look at this?

A few options to not have to put `if(Raven)` guards all over your code base:

* Hide `Raven` access inside your own service with appropriate guard conditions
* If using a preprocessor like TypeScript or Babel, you could make use of JavaScript's [Optional chaining (?.)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining): `Raven?.config('https://example.com')`
* Catching the error with appropriate try/catch blocks so that the app can continue working
