### ISSUE TITLE
Possible false positive: dt-cdn.net

### ISSUE THREAD

**Issue by ghaydtner** [lightswitch05/hosts#231]
Hi Dan,

I believe dt-cdn.com is a false positive. dt-cdn is the Dynatrace CDN, I'm with Dynatrace and what's hosted there are only images for the website https://www.dynatrace.com/ like https://dt-cdn.net/images/ebook-observability-and-beyond-736-fc055ce3a0.png. 

Can you please check?

Thanks,
Gerald

**Comment by lightswitch05** [comment]
I do not block `dt-cdn.com`, but I do have `dt-cdn.net` in my list. Its been blocked since `Jun 25 2018` - added in https://github.com/lightswitch05/hosts/commit/8571b18a0291d8ce8c2b6a5deca1fdbf8a174a28

If you can confirm that `dt-cdn.net` (not `.com`) is only used for hosting images for your website and isn't involved with advertising or any type of user/error tracking, then I'll take your word for it on good faith and remove it from the list.

**Comment by ghaydtner** [comment]
Hi Dan,

Yes, I was referring to dt-cdn.net and yes, it is just used for website images.

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/99b3d4dbf77d756638098e3acb986c60f0f45abd#diff-edc11c36d2775f8d86fa6210e66d8cfdL174454

I appreciate the information and especially the transparency that you work with Dynatrace. I'm sorry about the false positive!
