### ISSUE TITLE
Issue accessing Teslarati.com

### ISSUE THREAD

**Issue by martinkuna** [lightswitch05/hosts#241]
I tried to access teslarati.com, it was blocked by my PiHole, I queried my lists and found two partial matches for teslarati
```
simple-cf-teslarati-com-edge.ntv.io 
teslarati-com-edge.ntv.io
```

Removing/whitelisting `teslarati-com-edge.ntv.io` and am now able to access Teslarati.com, but if I add it back in (and clear my dns cache), I can no longer, any ideas?

**Comment by lightswitch05** [comment]
Looks like `www.teslarati.com` is a CNAME for `teslarati-com-edge.ntv.io`. I have the root `ntv.io` blocked - and so subdomains are automatically found and added to the list. The root domain was originally added in commit https://github.com/lightswitch05/hosts/commit/51ccd44bd9ec6caea201ae83b059585e47e5683c.

[A lot of people block the root domain](https://blocklist-tools.developerdan.com/entries/search?q=ntv.io). However, it looks like I'm the only one blocking `teslarati-com-edge.ntv.io`. Since this is limited to a single domain, I'm happy to whitelist it.

**Comment by lightswitch05** [comment]
Removed in https://github.com/lightswitch05/hosts/commit/83c147b2f4304da1f1bfcca8e22eec1f15b5da27 - thanks for the informative report!
