### ISSUE TITLE
free junk domains :)

### ISSUE THREAD

**Issue by ghost** [lightswitch05/hosts#259]
Hi I discovered your project by investigating some other blacklist url and discovered you like blocking hate and fake news like I do, and you're really good at discovering subdomains.

I went ahead and diff'd our files and I discovered I have about 4,000 more than you, but don't be too worried most of these are blogspot.abc duplicates. There might be a couple false positives, but I'm pretty sure you'd agree at least 98% is a perfect complement to your junk filter.

Most of these are racist sites/blogs. A handful are fringe leftists dedicated to exposing the war mongering mainstream media against did-nothing-wrong dictators. Apart from that I think that's pretty much it.

https://pastebin.com/JkRiaDnq

I also a have a filter dedicated to witchcraft/satanism (~2000 lines). Some in that are nazi satanism, but most are not. I'll let you decide if it's junk.
https://pastebin.com/TvxeRPMR

There's of course another reason to block junk domains besides children, do I really trust these sites to not be hacked, have malware, throw me cookies, or leak my ip address? I sure don't and I never want my computers talking to their computers :)

**Comment by lightswitch05** [comment]
Thanks @seth1 - I don't know when I'll be able to get around to looking at these, but I'll definitely have a look and let you know what I decide 👍

**Comment by lightswitch05** [comment]
Unfortunately the links are 404s now. It takes a lot of time for me to go though lists and verify them, which also means I tend to neglect them since there are a lot of other things competing for my attention. I'm sorry I was not able to look at these. In the future, it would be more productive to just give a few domains at a time. That way I could easily do a quick review and make a decision on them vs. needing to set aside a bunch of time to do a major review.

Full disclosure, I'm not really a fan of just adding a bunch of random domains. This project is about a curated listed of domains that I've found worthy of being blocked. There are a ton of other projects out there that love adding every list or domain variation they can find.
