### ISSUE TITLE
A few potential false positives

### ISSUE THREAD

**Issue by mkb2091** [lightswitch05/hosts#262]
You'd asked me to report domain's from your list that I added to my whitelist, and I realised I've not been doing that.

`credit.finance.intuit.com` - The domain is needed for checking your credit score via the Mint mobile app
`post.spmailtechnol.com` - SMTP provider
`sat1.us1-1.nanorep.co` - CNAME for `help.mint.com` the support site for `mint.com`
`h-ebay.online-metrix.net` - CNAME for `src.ebay-us.com` which is needed for external logins to ebay
`secure.indeed.com` - The domain is used for user account login on an employment website. The domain being blocked prevents the webpage from displaying to login.

**Comment by lightswitch05** [comment]
* `credit.finance.intuit.com`: I didn't use the credit score feature when I used to have Mint, so that makes sense when I didn't notice the break. This one is from 2018 - so my notes are not good about why I added it. I'll remove it.
* `post.spmailtechnol.com`: My notes say `CNAME for tracking spgo.io` - which is a SparkPost tracking domain. Interesting that its no longer a CNAME and the IP addresses are different. Still seems fishy that it used to just be a CNAME.... but unfortunately my notes don't give me any more info 
* `sat1.us1-1.nanorep.co`: Nano rep does do tracking and I believe upselling as well, but I suppose they do provide support as well - I'll consider moving to aggressive
* `h-ebay.online-metrix.net`: I just logged in without issue, so I'm not able to verify any loss of functionality. This is the first I've heard of this one.
* `secure.indeed.com`: Notes show a tracking XHR request from this domain `https://secure.indeed.com/rpc/log?a=onetap_action&oneTapA=LibraryCalled&clVer=0.3.4&googTapClientTK=[REDACTED]&`. I just tested and verified that its broken, I'm good with removing this one.

**Comment by lightswitch05** [comment]
I forgot to say thanks for the great feedback and detailed ticket!

**Comment by dnmTX** [comment]
@lightswitch05:

> h-ebay.online-metrix.net: I just logged in without issue, so I'm not able to verify any loss of functionality. This is the first I've heard of this one.

@mkb2091 is obviously using NextDNS which,even if the CNAME is listed here only will block everything 
related to it(domain,aliases etc.). 
I'm not saying,remove it,but make your decision based on that info.

**Comment by lightswitch05** [comment]
![image](https://user-images.githubusercontent.com/598803/109690091-f651f380-7b53-11eb-9b87-1dc616cd2829.png)
I don't even see `src.ebay-us.com` being used? I'm using PiHole - which also does CNAME blocking - but it doesn't do wildcard/subdomain blocking.

**Comment by dnmTX** [comment]
In this case @mkb2091 might need to provide the link to that **external login** he mentioned in his first post i guess.

**Comment by mkb2091** [comment]
I have not actually tested it myself, just had it reported and thought it looks legit so removed it from my consolidated list which has a lower removal threshold. I don't have any more information about it, so can't prove whether it actually is needed

**Comment by dnmTX** [comment]
Well i just had to Google `src.ebay-us.com` and nothing good showed up:
https://www.ghacks.net/2020/05/25/ebay-is-port-scanning-your-system-when-you-load-the-webpage/
...which led me to making recommandation of blocking this domain altogether.

**Comment by lightswitch05** [comment]
Looks like I've already taken action on the ones I could verify. Thanks again for the info!
