### ISSUE TITLE
[False positive] ubiservices.data.ubi.com

### ISSUE THREAD

**Issue by Rogacz** [lightswitch05/hosts#270]
This is blocking ubi connection for save sync.
I wanted to download saves from PS4 to PS5 and this only works with ubisoft save sync.
When I opened a game on PS5 I got error 0x20101904 and no save was available, 
once I've whitelisted ubiservices.data.ubi.com I got no errors and my save games were available.

**Comment by lightswitch05** [comment]
Thanks for the report @Rogacz. It looks like `data.ubi.com` is a common block and is just a CNAME for `redirect622.tagcommander.com`. My list auto-expanded that domain to include `ubiservices.data.ubi.com`. Since this appears to be limited to Ubi and is breaking functionality, I'm happy to remove it. It will be removed in the next list update.

Thanks for the report!
