### ISSUE TITLE
Italian SPID identity system from Poste not working

### ISSUE THREAD

**Issue by fakezeta** [lightswitch05/hosts#277]
Hi,

posteitalianespa.sc.omtrdc.net host is filtered from "ads and tracking extended" used by Poste provider for italian public identity service called SPID.
Whitelisting this host makes the service work.

I've try looking for a reason it was included but could not find anything.

Thank you for your work anyway

**Comment by lightswitch05** [comment]
Hello @fakezeta - I'm not sure how this ticket missed my attention. I'm am sorry that it has taken me so long to reply.

Since hosts files cannot block on wildcards, I use various tools to find subdomains of any root domain that I have blocked. This is one of those cases. `omtrdc.net` is the domain used by Adobe's Omniture  - an [advertising and tracking tool](https://www.eff.org/deeplinks/2009/08/behavioral-tracking). And so my tools automatically discovered and added `posteitalianespa.sc.omtrdc.net` to the list.

Could you supply a link or a more detailed set of instructions so that I can verify the broken service?

**Comment by fakezeta** [comment]
You're welcome :)

login page for Poste managed SPID is [https://posteid.poste.it/jod-securelogin-schema/login.jsp](https://posteid.poste.it/jod-securelogin-schema/login.jsp )

Anyway I just tried again disabling my custom whitelist entry and the service no more makes a call to `posteitalianespa.sc.omtrdc.net` so we can close the ticket.

Again, thank you for your valuable effort
