### ISSUE TITLE
[BUG] empty lines

### ISSUE THREAD

**Issue by dnmTX** [lightswitch05/hosts#278]
Hi @lightswitch05, i was playing with my scripts today and noticed that at the end of the file there are several empty lines.
And just FYI,your file is so big that my one liners started chocking on it 😉 ,any ideas coming to your mind to kind of...shrink it...
i guess(on your end)? 
I'm doing my best on my end,trust me. I kind of cut it on half due to the dnsmasq's ability to block TLD's and wildcard blocking as well aaand it's still too big 🤔 

P.S. Removing those empty lines might save some...micro seconds on my script though(give it some break) 😄

**Comment by lightswitch05** [comment]
I like a blank line at the end. I actually there was a PiHole bug in the past year where the last line was ignore if there wasn't a following blank line. I just deleted about ~2k domains that seemed to all be pointing to the same CNAME - so that will help a bit.

The reality of it is that HOSTS file format isn't great and that one of these days I should release the lists in a different format. Another reality is that I have very little time to spend on personal projects. I'm able to maintain this one because I already did so much work setting it all up to make it easy to manage - but if I were forced to start over again, I just wouldn't have the time to do it. 🤷‍♂️ 

My other project - [BlockList Tools](https://blocklist-tools.developerdan.com) - is about to die because I don't have time to redesign the database to be space efficient. Or at least I'll have to delete a lot of the larger (and poor quality) lists from it. Lots of things I want to do. Perhaps one day I'll win the lottery and be able to dedicate my entire time on fun free things like this 😉

**Comment by dnmTX** [comment]
> I like a blank line at the end

@lightswitch05  it's more then one,htere are probably four total!

>  I should release the lists in a different format

and what kind of formats you have in mind?

**Comment by lightswitch05** [comment]
I guess Adblock format is the most flexible

**Comment by dnmTX** [comment]
So on the subject of those empty lines,did you make up your mind so i can close this or i still have to bugging you about it 😄

**Comment by lightswitch05** [comment]
Please leave it open and I'll get to it when I'm able to 👍

**Comment by lightswitch05** [comment]
The next release will have one extra blank line removed

**Comment by dnmTX** [comment]
So three left,why even bother?

**Comment by lightswitch05** [comment]
> So three left,why even bother?

Nope, there are only two blank lines. Now there will be one blank line.

> why even bother?

Cause you opened this ticket for me to fix?

**Comment by lightswitch05** [comment]
`$` being new line characters:

![image](https://user-images.githubusercontent.com/598803/125976719-7d94da53-b344-46e4-a1bb-dfb069e0e6c5.png)

**Comment by dnmTX** [comment]
My apologies but last time i checked(probablly whenever i opened the ticket) there were four empty lines at the very end.
One is fine,almost every list has it,for some reason.

> Cause you opened this ticket for me to fix?

Sure i did and thanks for getting back to it 👍
