### ISSUE TITLE
[False Positive] Datadog

### ISSUE THREAD

**Issue by ThePowerOfDreams** [lightswitch05/hosts#284]
Hi,

Dozens and dozens of Datadog hosts are in your list, even though many are clearly irrelevant (PyPi for instance). Also, Datadog is used for infrastructure monitoring, not ad/monetization/user tracking.

Could you please reconsider their inclusion?

**Comment by lightswitch05** [comment]
Datadog is for generic data collection. It is certainly used for infrastructure monitoring, but is also used for other data collection as well.

[From their website](https://www.datadoghq.com/solutions/real-time-business-intelligence/) (emphasis added):
> Datadog enables organizations to instrument and analyze application-level business activity by **collecting metrics such as** purchases processed, traveler check-ins, or **ad impressions**.

Datadog also works with 3rd party integrations. Datadog collects the data, and the integration service consumes that data for various purposes. As an example, here is an [automate.io integration](https://automate.io/integration/campaign-monitor/datadog)

> Boost efficiency of your internal processes and automate your operations in Datadog. Gather leads, trigger automated emails and put your email marketing on autopilot in Campaign Monitor. Do much more by connecting Campaign Monitor and Datadog. 

----

Having said all that, there are certainly _good_ uses of Datadog as well, such as monitoring outages and error reporting. I encourage users of this list to make up their own mind what should be allowed and what should be blocked, and so I encourage you to whitelist Datadog on your side if you believe it should not be blocked. However, I will not be removing it from the list. I hope I have been able to explain to your satisfaction why I added them to the list.

**Comment by dnmTX** [comment]
@lightswitch05 what can you tell me about `r20.rs6.net` ? I couldn't open a link yesterday because of it that didn't come from some random website.

**Comment by f0o** [comment]
Only
```
browser-http-intake.logs.datadoghq.com
rum-http-intake.logs.datadoghq.com
mobile-http-intake.logs.datadoghq.com
```

should be blocked the rest has nothing to do with tracking but infrastructure management and monitoring. Banning whole of Datadog because of a secondary feature that I've yet to see being actually used anywhere in the industry is plain stupid.

I'd suggest filtering out the ad-list and removing anything datadog-related after downloading it. @ThePowerOfDreams

**Comment by lightswitch05** [comment]
Thanks for your opinion @f0o. I don't have the time or willpower to go through every subdomain of every blocked root domain and determine which ones are specific to tracking and which ones are not. This uses three tools to go out and find subdomains to any root domain I've added, and automatically add those subdomains to the list as well.

* VirusTotal
* Certificate Transparency logs
* Common Crawl

Because of how useful and effective these tools are, I regularly add root domains to the list. Some people disagree with this strategy, and so my list is likely not a good fit for their needs. I also encourage all users of these lists to whitelist entries as they see fit and to not see an entry on this list as some sort of moral stance where I'm saying something 'should' be blocked or to make the mistake that domains on the list are morally bankrupt. It is simply a list of domains that might be used for ads or tracking (or another category).

This seems like an emotinally charged ticket. So I'm going to copy & paste a snippet from my issue template:

> I really don't want to create a 'code of conduct', but if you need some guidelines on your expected behavior, checkout this 'Hey Friend' song first https://vimeo.com/338708688

I don't normally do this, but I want to emphasize how this list works. Here are all the domains for `datadoghq.com` that I have along with their source. If the source is `curated`, then that means I added it directly. You'll see I've added the root domain, and that allow the various tools to go out and discover a bunch of subdomains on their own.

| name | source |
| :--- | :--- |
| collector.datadoghq.com | common-crawl |
| datadoghq.com | common-crawl |
| api.datadoghq.com | common-crawl |
| app.datadoghq.com | common-crawl |
| docs.datadoghq.com | common-crawl |
| dd-corpsite.datadoghq.com | common-crawl |
| datadogon.datadoghq.com | common-crawl |
| ad.datadoghq.com | common-crawl |
| chat.datadoghq.com | common-crawl |
| browser-http-intake.logs.datadoghq.com | common-crawl |
| browser-http-intake.logs.datadoghq.com | curated |
| api.datadoghq.com | curated |
| datadoghq.com | curated |
| collector.datadoghq.com | curated |
| 7-29-0-app.agent.datadoghq.com | virustotal |
| email.datadoghq.com | virustotal |
| outbound.datadoghq.com | virustotal |
| mic.datadoghq.com | virustotal |
| us3.datadoghq.com | virustotal |
| beta-intake.profile.datadoghq.com | virustotal |
| intake.profile.datadoghq.com | virustotal |
| auhome.datadoghq.com | virustotal |
| streaming-docs-collector.datadoghq.com | virustotal |
| dd-corpsite.datadoghq.com | virustotal |
| nulltags.datadoghq.com | virustotal |
| nt.datadoghq.com | virustotal |
| streaming-collector.datadoghq.com | virustotal |
| streaming-ios-collector.datadoghq.com | virustotal |
| 5-8-4-app.agent.datadoghq.com | virustotal |
| hwcdn.datadoghq.com | virustotal |
| fornex.datadoghq.com | virustotal |
| dmealkit.datadoghq.com | virustotal |
| collector-26.datadoghq.com | virustotal |
| 10zy.datadoghq.com | virustotal |
| cla-26.datadoghq.com | virustotal |
| api.datadoghq.com | virustotal |
| u002fwww.datadoghq.com | virustotal |
| dpay-dev.datadoghq.com | virustotal |
| ssc.datadoghq.com | virustotal |
| square.datadoghq.com | virustotal |
| premier-agent.datadoghq.com | virustotal |
| zgm.datadoghq.com | virustotal |
| opensource.datadoghq.com | virustotal |
| streaming-android-collector.datadoghq.com | virustotal |
| production-iress.datadoghq.com | virustotal |
| itx.datadoghq.com | virustotal |
| brother-scms-b1-prd.datadoghq.com | virustotal |
| zillow-offers.datadoghq.com | virustotal |
| zillow.datadoghq.com | virustotal |
| datainfra.datadoghq.com | virustotal |
| ai-platform.datadoghq.com | virustotal |
| zg-search.datadoghq.com | virustotal |
| cvent.datadoghq.com | virustotal |
| store.datadoghq.com | virustotal |
| wastemanagement.datadoghq.com | virustotal |
| learn.datadoghq.com | virustotal |
| www.datadoghq.com | virustotal |
| agent-intake.logs.datadoghq.com | virustotal |
| logs.datadoghq.com | virustotal |
| michelada.datadoghq.com | virustotal |
| imgix.datadoghq.com | virustotal |
| servicetags.datadoghq.com | virustotal |
| jobs.datadoghq.com | virustotal |
| docs.datadoghq.com | virustotal |
| w.datadoghq.com | virustotal |
| elb-web.datadoghq.com | virustotal |
| partlow.datadoghq.com | virustotal |
| studentpack.datadoghq.com | virustotal |
| 5-10-0-app.agent.datadoghq.com | virustotal |
| profile.datadoghq.com | virustotal |
| browser-http-intake.logs.datadoghq.com | virustotal |
| agent-http-intake.logs.datadoghq.com | virustotal |
| agent-443-intake.logs.datadoghq.com | virustotal |
| mobile-http-intake.logs.datadoghq.com | virustotal |
| docs-staging.datadoghq.com | virustotal |
| 6-6-0-app.agent.datadoghq.com | virustotal |
| cla.datadoghq.com | virustotal |
| chat.datadoghq.com | virustotal |
| metrics.datadoghq.com | virustotal |
| public-trace-http-intake.logs.datadoghq.com | virustotal |
| help.datadoghq.com | virustotal |
| redirectssuccessfuljobshistorylimittags.datadoghq.com | virustotal |
| binarytags.datadoghq.com | virustotal |
| 5-20-1-app.agent.datadoghq.com | virustotal |
| adb.datadoghq.com | virustotal |
| rental-platform.datadoghq.com | virustotal |
| staging-iress.datadoghq.com | virustotal |
| keys.datadoghq.com | virustotal |
| knts.datadoghq.com | virustotal |
| hostmaster.datadoghq.com | virustotal |
| 5-2-0-app.agent.datadoghq.com | virustotal |
| 9.agent.datadoghq.com | virustotal |
| 7-21-1-app.agent.datadoghq.com | virustotal |
| 7-24-0-app.agent.datadoghq.com | virustotal |
| 6-14-0-app.agent.datadoghq.com | virustotal |
| 5-32-1-app.agent.datadoghq.com | virustotal |
| n0m5-3-0-app.agent.datadoghq.com | virustotal |
| 5-25-1-app.agent.datadoghq.com | virustotal |
| 5-20-1-app-9.agent.datadoghq.com | virustotal |
| 7-21-0-app.agent.datadoghq.com | virustotal |
| 7-23-1-app.agent.datadoghq.com | virustotal |
| 6-20-7-app.agent.datadoghq.com | virustotal |
| process.agent.datadoghq.com | virustotal |
| 5-22-1-app.agent.datadoghq.com | virustotal |
| 7251app.agent.datadoghq.com | virustotal |
| 6-16-0-app.agent.datadoghq.com | virustotal |
| 6-13-0-app.agent.datadoghq.com | virustotal |
| 6-15-0-app.agent.datadoghq.com | virustotal |
| 7250app.agent.datadoghq.com | virustotal |
| 6-2-0-app.agent.datadoghq.com | virustotal |
| 6-9-0-app.agent.datadoghq.com | virustotal |
| 7-25-1-app.agent.datadoghq.com | virustotal |
| srvdc5-19-0-app.agent.datadoghq.com | virustotal |
| 5-21-2-app.agent.datadoghq.com | virustotal |
| 6-14-1-app.agent.datadoghq.com | virustotal |
| 5-21-1-app.agent.datadoghq.com | virustotal |
| 6-12-0-app.agent.datadoghq.com | virustotal |
| 5-32-2-app.agent.datadoghq.com | virustotal |
| 5-15-0-app.agent.datadoghq.com | virustotal |
| 5-32-7-app.agent.datadoghq.com | virustotal |
| 5-18-0-app.agent.datadoghq.com | virustotal |
| 5-32-8-app.agent.datadoghq.com | virustotal |
| 6-15-1-app.agent.datadoghq.com | virustotal |
| 7-19-2-app.agent.datadoghq.com | virustotal |
| 7-27-1-app.agent.datadoghq.com | virustotal |
| 5-29-0-app.agent.datadoghq.com | virustotal |
| 5-32-5-app.agent.datadoghq.com | virustotal |
| 5-22-0-app.agent.datadoghq.com | virustotal |
| 7-19-1-app.agent.datadoghq.com | virustotal |
| srv-prod-20165-19-0-app.agent.datadoghq.com | virustotal |
| 7-26-0-app.agent.datadoghq.com | virustotal |
| 7-16-0-app.agent.datadoghq.com | virustotal |
| 9-18-4-app.agent.datadoghq.com | virustotal |
| srv-prod-20125-19-0-app.agent.datadoghq.com | virustotal |
| 5-14-1-app.agent.datadoghq.com | virustotal |
| 6-1-2-app.agent.datadoghq.com | virustotal |
| 7-19-0-app.agent.datadoghq.com | virustotal |
| 6-3-3-app.agent.datadoghq.com | virustotal |
| 5-28-1-app.agent.datadoghq.com | virustotal |
| 6-11-0-app.agent.datadoghq.com | virustotal |
| 5-26-0-app.agent.datadoghq.com | virustotal |
| 0-10-7-app.agent.datadoghq.com | virustotal |
| 6-23-1-app.agent.datadoghq.com | virustotal |
| sr16-prod-20185-19-0-app.agent.datadoghq.com | virustotal |
| 6-11-3-app.agent.datadoghq.com | virustotal |
| 6-16-1-app.agent.datadoghq.com | virustotal |
| 5-32-6-app.agent.datadoghq.com | virustotal |
| 7-27-0-app.agent.datadoghq.com | virustotal |
| 5-32-3-app.agent.datadoghq.com | virustotal |
| 5-32-4-app.agent.datadoghq.com | virustotal |
| 5-22-3-app.agent.datadoghq.com | virustotal |
| 6-21-0-app.agent.datadoghq.com | virustotal |
| 6-17-1-app.agent.datadoghq.com | virustotal |
| 7-28-0-app.agent.datadoghq.com | virustotal |
| 1-12-0-app.agent.datadoghq.com | virustotal |
| 5-4-3-app.agent.datadoghq.com | virustotal |
| 7-20-2-app.agent.datadoghq.com | virustotal |
| k8s.agent.datadoghq.com | virustotal |
| 6-10-1-app.agent.datadoghq.com | virustotal |
| 6-12-1-app.agent.datadoghq.com | virustotal |
| agent.agent.datadoghq.com | virustotal |
| 7-25-0-app.agent.datadoghq.com | virustotal |
| 7-22-1-app.agent.datadoghq.com | virustotal |
| trace.agent.datadoghq.com | virustotal |
| m.agent.datadoghq.com | virustotal |
| 6-11-1-app.agent.datadoghq.com | virustotal |
| 7-17-1-app.agent.datadoghq.com | virustotal |
| engineering.datadoghq.com | virustotal |
| helm.datadoghq.com | virustotal |
| masklike.datadoghq.com | virustotal |
| viruscomix.datadoghq.com | virustotal |
| pcvirus.datadoghq.com | virustotal |
| labs.datadoghq.com | virustotal |
| ycacovda.datadoghq.com | virustotal |
| discovery.datadoghq.com | virustotal |
| mascaradelatex.datadoghq.com | virustotal |
| dockerproviderad.datadoghq.com | virustotal |
| datadoghq.com | virustotal |
| ac-xmpie-ag.datadoghq.com | virustotal |
| activedeadlinesecondsad.datadoghq.com | virustotal |
| agent.datadoghq.com | virustotal |
| 5-11-1-app.agent.datadoghq.com | virustotal |
| 5-10-1-app.agent.datadoghq.com | virustotal |
| 5-11-2-app.agent.datadoghq.com | virustotal |
| 5-11-0-app.agent.datadoghq.com | virustotal |
| 5-11-3-app.agent.datadoghq.com | virustotal |
| 5-12-1-app.agent.datadoghq.com | virustotal |
| 5-13-0-app.agent.datadoghq.com | virustotal |
| 5-12-3-app.agent.datadoghq.com | virustotal |
| 5-12-2-app.agent.datadoghq.com | virustotal |
| 5-16-0-app.agent.datadoghq.com | virustotal |
| 5-14-0-app.agent.datadoghq.com | virustotal |
| 5-17-0-app.agent.datadoghq.com | virustotal |
| 5-18-1-app.agent.datadoghq.com | virustotal |
| 5-17-2-app.agent.datadoghq.com | virustotal |
| 5-20-0-app.agent.datadoghq.com | virustotal |
| 5-19-0-app.agent.datadoghq.com | virustotal |
| 5-21-0-app.agent.datadoghq.com | virustotal |
| 5-20-2-app.agent.datadoghq.com | virustotal |
| 5-23-0-app.agent.datadoghq.com | virustotal |
| 5-5-1-app.agent.datadoghq.com | virustotal |
| 5-4-2-app.agent.datadoghq.com | virustotal |
| 5-3-0-app.agent.datadoghq.com | virustotal |
| 5-5-2-app.agent.datadoghq.com | virustotal |
| 5-7-2-app.agent.datadoghq.com | virustotal |
| 5-8-2-app.agent.datadoghq.com | virustotal |
| 5-7-1-app.agent.datadoghq.com | virustotal |
| 5-8-3-app.agent.datadoghq.com | virustotal |
| 5-8-1-app.agent.datadoghq.com | virustotal |
| 5-8-5-app.agent.datadoghq.com | virustotal |
| 5-9-0-app.agent.datadoghq.com | virustotal |
| 5-9-1-app.agent.datadoghq.com | virustotal |
| 6-1-3-app.agent.datadoghq.com | virustotal |
| 6-0-3-app.agent.datadoghq.com | virustotal |
| 6-5-2-app.agent.datadoghq.com | virustotal |
| 6-4-1-app.agent.datadoghq.com | virustotal |
| 6-7-0-app.agent.datadoghq.com | virustotal |
| elb-agent.agent.datadoghq.com | virustotal |
| amp.datadoghq.com | virustotal |
| unversioned.agent.datadoghq.com | virustotal |
| apm.datadoghq.com | virustotal |
| apt.datadoghq.com | virustotal |
| blend-prod.datadoghq.com | virustotal |
| corpsite-preview.datadoghq.com | virustotal |
| datadogon.datadoghq.com | virustotal |
| em.datadoghq.com | virustotal |
| doc.datadoghq.com | virustotal |
| www.email.datadoghq.com | virustotal |
| events.datadoghq.com | virustotal |
| go.datadoghq.com | virustotal |
| gems.datadoghq.com | virustotal |
| ideas.datadoghq.com | virustotal |
| hilton.datadoghq.com | virustotal |
| investors.datadoghq.com | virustotal |
| ip-ranges.datadoghq.com | virustotal |
| learrn.datadoghq.com | virustotal |
| intake.logs.datadoghq.com | virustotal |
| nessus-int-scanner-1.logs.datadoghq.com | virustotal |
| http-intake.logs.datadoghq.com | virustotal |
| live.logs.datadoghq.com | virustotal |
| nessus-scanner.logs.datadoghq.com | virustotal |
| nessus-scanner-1.logs.datadoghq.com | virustotal |
| nessus-scanner-3.logs.datadoghq.com | virustotal |
| measureoss.datadoghq.com | virustotal |
| rum-http-intake.logs.datadoghq.com | virustotal |
| lp.datadoghq.com | virustotal |
| nvitstg.datadoghq.com | virustotal |
| p.datadoghq.com | virustotal |
| palantir.datadoghq.com | virustotal |
| process.datadoghq.com | virustotal |
| pydoc.datadoghq.com | virustotal |
| pypi.datadoghq.com | virustotal |
| rjent.datadoghq.com | virustotal |
| starbucks.datadoghq.com | virustotal |
| static.datadoghq.com | virustotal |
| streaming-dash-collector.datadoghq.com | virustotal |
| synthetics.datadoghq.com | virustotal |
| t10tronc.datadoghq.com | virustotal |
| teachertoolbox.datadoghq.com | virustotal |
| trimble-security.datadoghq.com | virustotal |
| urlfilterad.datadoghq.com | virustotal |
| logs.vpce.datadoghq.com | virustotal |
| vad.datadoghq.com | virustotal |
| workshop.datadoghq.com | virustotal |
| yum.datadoghq.com | virustotal |
| zendesk.datadoghq.com | virustotal |
| app.datadoghq.com | virustotal |
| capone-prod.datadoghq.com | virustotal |
| rpm.datadoghq.com | virustotal |
| zocdoc.datadoghq.com | virustotal |
| partners.datadoghq.com | virustotal |
| fidelity.datadoghq.com | virustotal |
| collector.datadoghq.com | virustotal |
| koronalakopark.datadoghq.com | virustotal |
| nessus-int-scanner-3.logs.datadoghq.com | virustotal |
| nessus-scanner-2.logs.datadoghq.com | virustotal |
| torii.datadoghq.com | virustotal |
| countactivedeadlinesecondsad.datadoghq.com | virustotal |
| streaming-corpsite-collector.datadoghq.com | virustotal |
| nessus-int-scanner-2.logs.datadoghq.com | virustotal |
| 2fwww.datadoghq.com | virustotal |
| ab-inbev.datadoghq.com | virustotal |
| design.datadoghq.com | virustotal |
| global-abinbev.datadoghq.com | virustotal |
| venmo.datadoghq.com | virustotal |
| convoy.datadoghq.com | virustotal |
| instacart.datadoghq.com | virustotal |
| sap-abinbev.datadoghq.com | virustotal |
| eu-abinbev.datadoghq.com | virustotal |
| 6-14-2-app.agent.datadoghq.com | virustotal |
| 5-25-2-app.agent.datadoghq.com | virustotal |
| 6-20-2-app.agent.datadoghq.com | virustotal |
| 7-16-1-app.agent.datadoghq.com | virustotal |
| app.starbucks.datadoghq.com | virustotal |
| dd-integrations-core-wheels-build-stable.datadoghq.com | virustotal |
| naz-abinbev.datadoghq.com | virustotal |
| novcds.datadoghq.com | virustotal |
| jenkins.datadoghq.com | virustotal |
| network-devices.datadoghq.com | virustotal |
| 7-18-1-app.agent.datadoghq.com | virustotal |
| accenture.datadoghq.com | virustotal |
| cleo.datadoghq.com | virustotal |
| dexcom-prod.datadoghq.com | virustotal |
| tql.datadoghq.com | virustotal |
| sylob-dev.datadoghq.com | virustotal |
| sylob-prod.datadoghq.com | virustotal |
| gcp-encrypted-intake.logs.datadoghq.com | virustotal |
| tcp-encrypted-intake.logs.datadoghq.com | virustotal |
| http-encrypted-intake.logs.datadoghq.com | virustotal |
| lambda-tcp-encrypted-intake.logs.datadoghq.com | virustotal |
| csg.datadoghq.com | virustotal |
| n0mnvitstg.datadoghq.com | virustotal |
| help-5.datadoghq.com | virustotal |
| appgate.datadoghq.com | virustotal |
| status.datadoghq.com | virustotal |
| docusign-rooms.datadoghq.com | virustotal |
| appgate-1.datadoghq.com | virustotal |
| au-data-storage.datadoghq.com | virustotal |
| jchome-stg.datadoghq.com | virustotal |
| intrepidtravel.datadoghq.com | virustotal |
| orchestrator.datadoghq.com | virustotal |
| syk-jr-prod.datadoghq.com | virustotal |
| capone-nonprod.datadoghq.com | virustotal |
| hts.datadoghq.com | virustotal |
| 7-18-0-app.agent.datadoghq.com | virustotal |
| 7-28-1-app.agent.datadoghq.com | virustotal |
| 6-19-2-app.agent.datadoghq.com | virustotal |
| 7-24-1-app.agent.datadoghq.com | virustotal |
| 6-25-1-app.agent.datadoghq.com | virustotal |
| 6-28-1-app.agent.datadoghq.com | virustotal |
| 5-30-1-app.agent.datadoghq.com | virustotal |

**Comment by f0o** [comment]
Thanks for clarifying the sources, I appreciate the transparency. I'll check deeper when time allows to why ddog got listed at virustotal.

**Comment by lightswitch05** [comment]
I can answer that, DataDog is not listed by virustotal as being malicious. I use the VirusTotal API to [discover subdomains](https://developers.virustotal.com/reference#subdomains), it works for all domains and has nothing to do with a domain being listed/flagged or anything else.

**Comment by f0o** [comment]
Oooh ok I understand now 👍
