### ISSUE TITLE
[Breaks Functionality] - one entry breaks tubi video playback

### ISSUE THREAD

**Issue by whorfin** [lightswitch05/hosts#294]
This should not be blocked in order for tubi to actually play videos:
`manifest.production-public.tubi.io`

"The burden of proof is on you" ... well, the actual `m3u8` files for video streams are hosted on this server, so there is no way Tubi works without it.

eg
`https://tubitv.com/movies/588414/vampira-and-me`
will fail with this blocked; upon unblocking, you will see the meta-stream hosted here:
`https://manifest.production-public.tubi.io/ad2a89f0-5288-4d6f-8c66-ba8cf6a9e076/y7hfysadvf.m3u8?token=REDACTED&manifest=true`
and the individual content streams also there, eg
`https://manifest.production-public.tubi.io/ad2a89f0-5288-4d6f-8c66-ba8cf6a9e076/hwym33e7/stream.m3u8?token=REDACTED&manifest=true`
(which then ultimately load stream segments from an unblocked domain)

All the nonsense analytics you have nicely blocked, so thank you for that, it's just this one entry which breaks the platform.

**Comment by lightswitch05** [comment]
Hello @whorfin and thank you for such a detailed ticket! You clearly put in a lot of work here, and I apologize that I was not equally diligent in responding to you. 

`manifest.production-public.tubi.io` - I did not add this one directly to my list, it was auto-added because I have the entire root domain of `tubi.io` blocked in this list. It is interesting that you are able to get this thing working when Its supposed to be blocked entirely!

So, the next question is why the entire root domain of `tubi.io` is blocked. Lets check the notes.... I added it in Jul 2019. That means it was before I started taking detailed notes of each domain. The specific commit is here: https://github.com/lightswitch05/hosts/commit/06452b7197c031a3cdaf0a05b75f782df9b53d26 with the commit message: 

>Several ad domains from pihole. Added some chat widgets to aggressive list from various sources. Added Samsung Smartthings domain - unsure if it will cause issues or not.

So, no mention of `tubi.io` at all 😔.

[Searching against some other lists](https://blocklist-tools.developerdan.com/entries/search?q=tubi.io). It looks like I'm the only one blocking it. 
![image](https://user-images.githubusercontent.com/598803/129573141-bff5ed75-bdd0-46f3-9e5a-4a036669345a.png)

That is normally a bad sign.... not only do I not have a good reason to block it (that I remember at least), but my peers are not blocking it either. So, I could be convinced to remove this domain altogether, since it seems to be a bogus entry. However, you said:

> All the nonsense analytics you have nicely blocked, so thank you for that, it's just this one entry which breaks the platform.

Which is great! And those certainly would not have been blocked if I hadn't blocked the root domain of `tubi.io`.

Alright, so here is the plan. I don't use this service at all. That means I have no insights into whats required, what isn't required, and what new tracking domains they might add in the future. I'm going to whitelist `manifest.production-public.tubi.io`, but leave the root `tubi.io` in this list. That means everything will stay this same, with the one removal. In the future, if something else needs whitelisting, can I can on you to reach back out to me so that we can get it fixed again?

**Comment by lightswitch05** [comment]
removed in the next update

**Comment by whorfin** [comment]
Super, thanks!
I do note that with the blocklist the way it is, plus whitelisting `manifest.production-public.tubi.io`, the tubitv.com link i provide at the top (you do not need to register to attempt to watch the movie) throws a "you have an adblocker" error and will not play the movie.
Using an in-browser blocker like Ublock Origin set to disable anti-adblocker-blockers, everything is fine.
So that might be an argument to just totally remove `tubi.io`  and friends from your list, as the service is still technically broken unless one runs a blocker extension in-browser (or uses the tubi app[s])
I'm good either way, so I leave that to you, based on your learnings of what others are doing.
(tubitv works because of all the domain shenanigans; the website is `tubitv.com` though things are served from `tubi.io`)
