### ISSUE TITLE
False positive: cdn.rebelmouse.com

### ISSUE THREAD

**Issue by flaviut** [lightswitch05/hosts#301]
Looks like spectrum.ieee.org uses a subdomain of cdn.rebelmouse.com as their host:

![2021-09-14-173511_662x266_scrot](https://user-images.githubusercontent.com/5213469/133337163-240e6abf-0450-4b6e-ac57-f84d77c5ddec.png)

See https://spectrum.ieee.org/

**Comment by macbugs** [comment]
I agree, `cdn.rebelmouse.com` should not be blocked:

> www.protocol.com (→ www.protocol.com.cdn.rebelmouse.com) is blocked by
`Lightswitch05 - Ads & Tracking` and `Energized Regional Extension`.

Protocol.com is a legit business news site, and rebelmouse.com is a legit CDN.  They do say _["We make sure your brand is optimizing the right ad networks"](https://www.rebelmouse.com/creative-agency)_, but it does not appear that rebelmouse is actually serving the ads -- I only saw the usual suspects like doubleclick which are already blocked.

**Comment by lightswitch05** [comment]
`cdn.rebelmouse.com` is not - and has never - been blocked by my list. NextDNS is doing wildcard blocking of my list - which isn't how the list is meant to be used and is completely out of my control. https://github.com/lightswitch05/hosts/issues/358#issuecomment-1189371940

**Comment by ignoramous** [comment]
Echoing what Romain Contepas said, it be nice for Lightswitch05 to accomodate CNAME and wildcard-matching resolvers. Serverless DNS (which I co-develop) resorts to CNAME-chasing and wildcard-matching by default, too. AdGuard DNS does the same, afaik.

**Comment by lightswitch05** [comment]
> We would be more than happy to sponsor you, we know how time-consuming maintaining a blocklist is.

I appreciate the offer, but this repo is in maintenance mode per #356 - I just don't have the time or interest anymore. I'm glad people have found it useful but if it's causing issues I would recommend not using it since I'm not going to be making any big changes to it at this point and I only occasionally still add domains to it.

As for the CNAME blocking, I do use this list with Pihole and personally find it works well with the CNAME blocking it has implemented. The difference with NextDNS it seems is that it does wildcard CNAME blocking, which is a bit different and certainly more aggressive vs. pihole's exact CNAME blocking. It forces me to make a choice between having an exact domain blocked- which might be valid- or not having it blocked at all due to the wildcard nature of the blocking. The format of hosts files are lacking when it comes to allowlists and as been a major contributor to my growing disinterest with maintaining these lists.
