### ISSUE TITLE
Syntax error - line breaks is gone

### ISSUE THREAD

**Issue by ammnt** [lightswitch05/hosts#313]
Hi @lightswitch05

Thank you for your great project! I noticed that something wrong happen with your host file - some line breaks is gone and domains has been combined:

```
cloudgz-ecs.gravityzone.bitdefender.comin.getclicky.com
id.google.comin.getclicky.com
ims-prod06.adobelogin.comin.getclicky.com
nexus.officeapps.live.comin.getclicky.com
nexusrules.officeapps.live.comin.getclicky.com
api.accuweather.comwf.cbarsrv.com
azko.frwf.cbarsrv.com
checkipv6.quickconnect.towf.cbarsrv.com
cloudgz-ecs.gravityzone.bitdefender.comwf.cbarsrv.com
config.edge.skype.comwf.cbarsrv.com
connectivitycheck.gstatic.comwf.cbarsrv.com
f16.silaexpert02.frwf.cbarsrv.com
filedownload.lenovo.comwf.cbarsrv.com
google.frwf.cbarsrv.com
liveupdate.symantecliveupdate.comwf.cbarsrv.com
news.genapi.euwf.cbarsrv.com
push.bitdefender.netwf.cbarsrv.com
reservation.squashjeudepaume.comwf.cbarsrv.com
s.sspqns.comwf.cbarsrv.com
sv.symcd.comwf.cbarsrv.com
tile-service.weather.microsoft.comwf.cbarsrv.com
wfbssvc61.icrc.trendmicro.comwf.cbarsrv.com
whatismyip.akamai.comwf.cbarsrv.com
```

and more and more... Maybe you just want to know :) Please check! 

Thank you.
Cheers😙

**Comment by kowith337** [comment]
I feel like its not line break error, look at the end of entry, it will added `in.getclicky.com` and/or `wf.cbarsrv.com` at the end, probably `cbarsrv.com` and `getclicky.com` is the main site of tracking disguise.

**Comment by lightswitch05** [comment]
Hello, happy to explain what is going on here. I use various methods to discover sub domains of any root-domain I add to my list. One of those methods is VirusTotal, but unfortunately it also introduces some junk like you see here.

I have additional steps to verify all entries have valid DNS responses, however, some DNS servers use wildcarding, which means anything- even these junk entries- will still have a valid DNS response.

I go through and delete them from time-to-time, it's obviously been awhile since I've done it and so I need to do it again.

I hope that explains everything!
