### ISSUE TITLE
Unable to use your blocklists, did before.

### ISSUE THREAD

**Issue by StoGFly** [lightswitch05/hosts#326]
[i] Target: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
  [✗] Status: Connection Refused
  [✗] List download failed: no cached list available

**Comment by lightswitch05** [comment]
It's working for me. This list is hosted by GitHub, make sure you can access it directly and you are not having any DNS issues

**Comment by StoGFly** [comment]
I can see the link no problem in my browser, for some reason tho my pihole
can't see it... Strange right.

**Comment by RichardWissink** [comment]
I have the same. I can download the list from my windows PC browser OK.
wget from the Pi says the certificate is not valid.
pi@raspberrypi:~ $ wget https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
--2022-02-24 21:25:36--  https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
Resolving www.github.developerdan.com (www.github.developerdan.com)... 185.199.111.153, 185.199.109.153, 185.199.108.153, ...
Connecting to www.github.developerdan.com (www.github.developerdan.com)|185.199.111.153|:443... connected.
ERROR: The certificate of ‘www.github.developerdan.com’ is not trusted.
ERROR: The certificate of ‘www.github.developerdan.com’ has expired.

**Comment by lightswitch05** [comment]
This domain is entirely managed by GitHub and I have no control over it. `www.github.developerdan.com` is just a CNAME for `lightswitch05.github.io`

I suppose make sure your pihole isn't blocking `.io` domains? Since I do not control the domain, I can't really provide any details to you that wouldn't otherwise be available. The certificate is valid: https://www.ssllabs.com/ssltest/analyze.html?d=www.github.developerdan.com&hideResults=on&latest

**Comment by StoGFly** [comment]
Yea, weird one indeed. I haven't got the io domain blocked. I eventually
self hosted your lists for my own use.
