### ISSUE TITLE
cdn.ravenjs.com

### ISSUE THREAD

**Issue by gyCfjSnO** [lightswitch05/hosts#330]
The domain ```cdn.ravenjs.com``` is on blocklist ```Lightswitch05's Ads & Tracking``` and breaks the website ```https://www.reampedenergy.com.au/``` which is an Australian Energy Retailer. When it breaks the website images do not load and you are unable to login to the online portal to view/pay bills.

**Comment by gyCfjSnO** [comment]
Bump it has been a month since opening this issue.

**Comment by kowith337** [comment]
read #58

**Comment by gyCfjSnO** [comment]
> read #58

How do I pay my bills then?

**Comment by lightswitch05** [comment]
@gyCfjSnO if this domain is causing you issues, then you'll need to add it to an allowlist in whatever ad-block tool you are using. I'm not going to remove this entry over a single random website. Sentry does not provide a website-critical service, and if a website is breaking without sentry, it's simply due to a lack of proper error handling.
