### ISSUE TITLE
maxmind.com and subdomains... matter of opinion?

### ISSUE THREAD

**Issue by jawz101** [lightswitch05/hosts#55]
Personally, pfSense adblocker & firewall add-on, [pfBlockerNG](https://www.patreon.com/pfBlockerNG) uses Maxmind geoip library to recognize different countries' IP address ranges to generate firewall rules (ex: Say, I wanted to block all outbound traffic to North Korea & Iran).  Another open source project, [ntopng](https://www.ntop.org/products/traffic-analysis/ntop/), uses Maxmind's free geoip information to map what destinations your network communicates with.

I guess it's a matter of opinion, but they do offer their [country-level IP address information](https://www.maxmind.com/en/open-source-data-and-api-for-ip-geolocation) free of charge to the public to use in many different open source, privacy-oriented programs.

**Comment by lightswitch05** [comment]
Welcome back @jawz101 . Yes I’m definitely aware of Maxmind - I don’t think they are bad and deserve blocking on their own. But they do fall into a tracking category and strangly have a JavaScript subdomain. As far as their security and firewall rules go- JavaScript would not be the way to go about anything security related. JavaScript could only be useful in a tracking situation- which is why I decided to block them. I believe this is only in the aggressive list.

Anyways, that’s my logic on blocking it- from a client perspective blocking MaxMind makes sense. If you are running their services on a server, a whitelist would make sense.

**Comment by jawz101** [comment]
You too. Have a great New Year
