### ISSUE TITLE
wccftech.com

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#70]
`https://wccftech.com/amd-adrenalin-2019-edition-19-2-1-driver`
I found out
`dsh7ky7308k4b.cloudfront.net`
`s.ntv.io`
`s.skimresources.com`
`referrer.disqus.com`
`g.pcmag.com`
`cdn.static.zdbb.net`
`gurgle.zdbb.net`
`secure-us.imrworldwide.com`
`ns.zdbb.net`

**Comment by lightswitch05** [comment]
Hey, thanks @kyrios21 - while I definitely think there are some good blocks in this list, some of them a very commonly blocked in other lists already. I generally use [Steven Black's hosts](https://github.com/StevenBlack/hosts) as a rule of thumb when I add new hosts since his list is a combination of other well maintained lists.

**Comment by lightswitch05** [comment]
* `dsh7ky7308k4b.cloudfront.net` - adding
* `s.ntv.io` - In steven's list - but has a bunch of other subdomains not in the list, so adding it
* `s.skimresources.com` - In steven's list - but has a bunch of other subdomains not in the list, so adding it
* `referrer.disqus.com` - Not adding since its already blocked in steven's list
* `g.pcmag.com` - I'm not seeing this request, so not adding it
* `cdn.static.zdbb.net` - was already added to the extended list, but added it to the base list
* `gurgle.zdbb.net` - was already added to the extended list, but added it to the base list
* `secure-us.imrworldwide.com`- this is in steven's list, but it looks like they have a lot of location-based sub-domains, which is a good candidate for auto-expansion, so I'll add it to my list too
* `ns.zdbb.net` - was already added to the extended list, but added it to the base list
