### ISSUE TITLE
www.pcmag.com

### ISSUE THREAD

**Issue by kyrios21** [lightswitch05/hosts#71]
`https://www.pcmag.com/news/366348/instant-tethering-arrives-to-more-chromebooks-android-pho`
I found out
`zdbb.net`
`walker.zdbb.net`
Is it OK for me to post similar website? I mean websites which are (probably) in top of 500?

**Comment by lightswitch05** [comment]
I can't even load `pcmag.com` since they use InstartLogic hosting - which is a web-based rootkit provider and is blocked by my list: `www.pcmag.com. 58 IN CNAME a003.ziffdavis.inscname.net`

But I'm happy to add those two hosts. `zdbb.net` is blocked by Steven's project, but the subdomain `walker.zdbb.net` isn't - so I'll add them both
