### ISSUE TITLE
Hellcase

### ISSUE THREAD

**Issue by ArmynC** [lightswitch05/hosts#77]
The 'latest wins' and the roulete is broken.

I think that this is the faulty thing: `https://browser.sentry-cdn.com/4.6.4/bundle.min.js`

**Comment by dnmTX** [comment]
@ArmynC  you mind post a **LINK** so we can examine. Thanks.

P.S. Just FYI. If Sentry is the one causing this it wont be fixed for sure. See #58

**Comment by ArmynC** [comment]
https://hellcase.com/en/dailyfree

**Comment by dnmTX** [comment]
@lightswitch05  it is `browser.sentry-cdn.com`. It's way to embedded inside the whole free lottery thing.
Also @ArmynC  you need to allow Canvas on that site as well (just FYI). 
This site,don't matter that it's a part of Steam,because it's offering **free** weapons and shit it's a literary a DATA MINING HEAVEN. @ArmynC  would advise you to whitelist it on your end if you so eager to trade some non existing awards for your personal information(sort of).
At the end of the day the ball is in your court @lightswitch05 ,but i vote NO.Just going trough some of the scripts there,it's kind of....scary to say the least.

**Comment by lightswitch05** [comment]
Thanks for the info @ArmynC. Its pretty bad that the page fails when `browser.sentry-cdn.com` is blocked. Sentry would have nothing to do with the actual functionality of the website. If you are a regular user of the site, I recommend reaching out to their support and let them know their website breaks if `browser.sentry-cdn.com` fails to load. I'm sure they would be interested to hear about it. But in anycase, I don't intend to remove sentry from the list. It does not provide any critical functionality and websites the break due to it being blocked are doing a poor job of error handling.

**Comment by lightswitch05** [comment]
Just for documentation this is why their website breaks:

```
    Sentry.init({
        dsn: 'https://0f09a0558478408dba3aa948bafe4f56@sentry.io/1406135',
        environment: 'production'
    });
```

It could be fixed with a simple check:

```
if (Sentry) {
    Sentry.init({
        dsn: 'https://0f09a0558478408dba3aa948bafe4f56@sentry.io/1406135',
        environment: 'production'
    });
}
```

**Comment by dnmTX** [comment]
looks like everything i posted earlier is a nonsense so i'll delete my post 😒

**Comment by dnmTX** [comment]
Also found on `sourceforge.net`:
`snap.licdn.com`   URL: `https://snap.licdn.com/li.lms-analytics/insight.min.js`

Looks like it's part of **Linkedin** so if you planning to add it check if it breaks something there i guess.
Blocking it on Sourceforge doesn't affect anything.

**Comment by ArmynC** [comment]
Yeah, they got all fixed :+1:
