### ISSUE TITLE
gleam.io false positive

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#90]
Please remove these lines:

```
0.0.0.0 js.gleam.io
0.0.0.0 www.js.gleam.io
```

The domain is used to serve Javascript from the `gleam.io` giveaway platform/site.

Example of breakage:
```
https://youtooz.com/pages/pyrocynical-giveaway
http://www.365giveaways.com/amazongiftcardgiveaway.html
```

**Comment by lightswitch05** [comment]
Thanks for your comment @llacb47 . I gotta say, these look like straight up advertisements to me. Not only am I convinced they are advertisements, but they block access to known VPNs (I regularly use a VPN when checking these things out so that I don’t have to disable my local network settings). The fact that they block VPN access makes me think they are doing some serious user tracking & fingerprinting. So, beyond them being ads, they are tracking people and actively blocking those that avoid being tracked via VPN. Since it’s in my ads & tracking list- that’s two strikes against it.

I’m happy to leave this ticket open for a while incase anyone else wants to add their two cents. Change my mind?

**Comment by dnmTX** [comment]
> Change my mind?

nope

**Comment by llacb47** [comment]
It seems only the embeds on third-party sites are broken, the giveaway can be entered from `gleam.io` just fine.
