### ISSUE TITLE
Remove standardjs.com

### ISSUE THREAD

**Issue by feross** [lightswitch05/hosts#94]
The readme says:

> If you find something in a list that you believe is a mistake or breaks functionality, please open a ticket and I'll consider removing it

This commit (https://github.com/lightswitch05/hosts/commit/e981c682b4968136e592dcfc25aafb2b0a06eddd) blocks `standardjs.com` which is not an ad server and does not collect analytics. It seems inappropriate to be on a list of ad servers. It appears to have been added for dubious reasons given that blocking it won't actually reduce ads. This change will needlessly break this site.

**Comment by lightswitch05** [comment]
It’s a fair request, but I do not have intentions to remove it at this time. I’ll be happy to leave the ticket open for tracking.

From my point of view as someone who does not use this project - but regularly contributes to open source. If I wish to donate my time by submitting a pull request to another open source project- one that happens to use your tools- then I will be subjected to advertising. As a third party- not even using your tools, I think it’s intrusive to be subjected to your ads. Unless there is another course of action- such as NPM giving the ability to blacklist entire packages (see request https://npm.community/t/blacklist-entire-packages/9659)- then I don’t have any real recourse then to just discourage the use of your tools in the first place.

As I said in https://github.com/standard/standard/issues/1381#issuecomment-524421896 ,

> The package maintainers are welcome to do as they see fit

In the case, unless you have other options to suggest to me, I see fit to discourage the use of your tools by blocking your website in my list. Again, I totally agree that it’s a shit and non-effective solution to the Advertising you created- but it’s the only tool I have available.

**Comment by fregante** [comment]
@lightswitch05 this looks petty and does not follow what your repo description says. Are you also going to block google.com because they own AdSense and thus are the ruin of the Internet? Don’t use standard 14 if you don’t like it but there’s no need to block the whole site in the browser, for the reasons @feross mentioned.

**Comment by lightswitch05** [comment]
Thanks for your comment @fregante . I’m not overly concerned about the credibility of my personal ad and tracking prevention hosts file 😀.

I certainly do not use standard 14 and do not particularly like the defined rules. The point I take issue with is that I will very likely end up seeing these ads on my own system regardless of me using standard 14- dependencies and such. 

@fregante you certainly do not have to use my hosts file. And lucky for you, it will never accidentally get installed into your system since it isn’t bundled into any package managers.

**Comment by distransient** [comment]
> The point I take issue with is that I will very likely end up seeing these ads on my own system regardless of me using standard 14- dependencies and such.

😮 

You should really add http://registry.npmjs.org/ to your ad blocking hosts file to stop this!

**Comment by anudeepND** [comment]
https://www.zdnet.com/article/npm-bans-terminal-ads/

**Comment by feross** [comment]
I ended the funding experiment https://feross.org/funding-experiment-recap/

**Comment by lightswitch05** [comment]
Yes, I saw. This ticket was resolved by https://github.com/lightswitch05/hosts/commit/b2b9f00d339375560aba4173d69dccd96b7ffd91
