### ISSUE TITLE
Paywall hosts

### ISSUE THREAD

**Issue by llacb47** [lightswitch05/hosts#98]
Hello,

I don't know if it's in the scope of this list, but the following hosts are used to serve paywalls on newspaper sites. 

```
MediaPass - is used on tooeleonline.com, theislandnow.com, etc.
See https://publicwww.com/websites/%22MediaPass.init%22/

www.mediapass.com

ConneXt - see https://github.com/mg2connext/connext/wiki, flittz.com, and www.marketingg2.com/digital-mkt-tech/customerengagement.html
Also see https://publicwww.com/websites/%22collectors%22%3A%5B%22connext%22%5D/

cdn.czx5eyk0exbhwp43ya.biz
cdn.ayc0zsm69431gfebd.info
cdn.ayc0zsm69431gfebd.xyz
g2insights-cdn.azureedge.net
loader-cdn.azureedge.net
fp-cdn.azureedge.net
flittz-cdn.azureedge.net
prod-mng-proxy-connext.azurewebsites.net
connext-cdn.ec.azureedge.net
```

If you would like, you can add this to your list. If you have any questions, I hope I can answer them. 

(Also, have you ever considered adding hosts to your list that are `third-party` blocked or totally blocked on EasyList/EasyPrivacy?)

Thanks.

**Comment by lightswitch05** [comment]
Hey @llacb47, thank you for opening this ticket.

> have you ever considered adding hosts to your list that are third-party blocked or totally blocked on EasyList/EasyPrivacy

I have considered it and decided not too. This is my list of domains that I validate and maintain. I'm not interested in having to maintain someone else's decisions.

> Paywall hosts

I'm not particularly interested in blocking these directly. However, I am interested in blocking advertising and tracking. The mediapass script is injecting advertising, so that is enough to get it blocked:

`https://www.mediapass.com/static/js/mm.js`

    adroll_adv_id="ZYV54BWPE5CLBPRRKA5S7G

> ConneXt

This is just flat out marketing and tracking - I don't see anything paywall related to this. I'll block the domains I'm able to verify.

**Comment by lightswitch05** [comment]
For tracker purposes, these are the sites I did validation on:

* `https://www.denverpost.com/`
* `https://theislandnow.com/ `

**Comment by lightswitch05** [comment]
Closed by commit https://github.com/lightswitch05/hosts/commit/843a629b23bcdd6456c49a4dd6dc6c05b43ee082 - thanks for the details!
