### ISSUE TITLE
Report Tracker for Windows App

### ISSUE THREAD

**Issue by DRSDavidSoft** [lightswitch05/hosts#99]
These domains belong to [FlashGet](http://flashget.com), which is a Windows download manager app:

### Trackers
```
stat.flashget.com
supertracker.flashget.com
cplog.flashget.com
```

### Ads
```
post.7p.com
```

Could you please consider adding them to your list?

**Comment by anudeepND** [comment]
@DRSDavidSoft Thanks for reporting, I will add them in the next update

**Comment by lightswitch05** [comment]
Hello @DRSDavidSoft. I'm happy to add the flashget domains. I was waiting to add them so that I could check it out for myself - but looking at it now, there is no way I would install that on my computer. Also, the last update was 7 years ago - so beyond it looking sketchy, its very out of date.

There is a lot more download managers out there, maybe give this one a try: [Persepolis Download Manager](https://persepolisdm.github.io/)

I wasn't able to verify the `post.7p.com` host. But looking into its subdomains, it seems pretty clearly to be Ad related, so I'll add it too. If you care to give me a link with an Ad from 7p.com - just for tracking purposes, then I would be thankful.

**Comment by lightswitch05** [comment]
Closed by commit https://github.com/lightswitch05/hosts/commit/7036cfce3f21f9835e14c0c78cff9896696062ba
